version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Run unit tests (which also downloads dependencies)
          command: |
            go test ./...
      - run:
          name: Do static code analysis
          command: |
            ./.circleci/static-checks
      - run:
          name: Run e2e tests
          command: |
            ./e2e/cmdline
