version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Run unit tests (which also downloads dependencies)
          command: |
            go test ./...
      - run:
          name: Do static code analysis
          command: |
            # TODO: I feel like there should be a way to specify
            # necessary binaries in the go.mod file and then they will
            # get installed whenever you do things to download the
            # modules. But I don't know the answer so I'm doing what I
            # know namely 'go get' to install things.
            go get golang.org/x/lint/golint
            go get github.com/kisielk/errcheck
            ./.circleci/static-checks
      - run:
          name: Run command-line e2e tests
          command: |
            ./e2e/cmdline
      - setup_remote_docker
      - run:
          name: Build and Run Application Image
          command: |
            docker build -t records .
            docker run -p '8080:8080' records
          background: true
      - run:
          name: Run API e2e tests
          command: |
            ./e2e/run-api-e2e-tests
