#!/bin/bash -e

output=$(go run main.go e2e/invalidData.txt e2e/nonexistent.txt)
wantOutput=$(cat <<EOF
Invalid Input:
e2e/invalidData.txt:1: there should only be one type of separator in a single line but multiple separators ('|', ',') were specified
e2e/invalidData.txt:3: there were only 3 fields when there should have been 5
e2e/nonexistent.txt: file does not exist
EOF
)
if [ "$output" != "$wantOutput" ]
then
    echo "When running the command line app on invalid data, got output:
$output"
    echo "Want output:
$wantOutput"
    exit 1
fi
